### ISSUE TITLE
Get more models working for landing page

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#179]
the landing page backend should execute the specific model it is given instead of the demo model.

**Comment by miguelalba** [comment]
Since not all the models will run, we should list those that do in a separate file and disable the execution for the models that do not run or have errors. A simple JSON file with the following structure would be enough:

```json
{
 <model_id>: true,
 <another_model_id>: false
}
```

The model ids are the ones from general information >id like used for the plots and execution and upload times. This file can be placed under files/ or in a separated folder like *uploadDateTime*.

**Comment by schuelet** [comment]
- most RAKIP models run, though some are very slow (2min+) even on the default simulations
- Package gsl does not work
- Package r2OpenBugs can't find the openbugs program on the computer
- IMPORTANT NOTE: PiresOutblA2011-Salmonells.fskx had a faulty Salmonella-all.csv file resource which I fixed manually (some entries had a newline character, breaking the file). R seems to ignore it, but Renjin (and KNIME CSV Reader) cant read the file properly).

**Comment by llavall** [comment]
@schuelet are you updating the fskx file in the official DB as well or just in your local version? Who needs to be informed about that issue?

**Comment by schuelet** [comment]
we abandoned renjin as a possible alternative for the KNIME execution environment.
