### ISSUE TITLE
Joiner Bug: incorrect suffix index of combined submodels

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#204]
The parameter id's of nested models (>2 submodels) is only correct for the simple models and the full combined model. If a submodel is also combined, the parameter id's have too many suffixes (from the full combObj). 
- Full combinded model: Parameter ID: x11
- submodel (combined): x11    <-- error, it should say "x1"
- simple model: x

Possible cause:
In the joiner node model line 833, the system checks if a combined model exists in the fskID_to_fskObject map, before it sets the resets the Suffix. The problem is, that a combined model has a concatenated name which is not part of fskID_to_fskObject and therefore it doesn't update the suffixes correctly.

**Comment by ahmadswaid** [comment]
@schuelet which branch have tested on your finding, so I can reproduce? in the 4.0.x and frontend-maven-plugin-support, I found the joined model is runnable.

**Comment by ahmadswaid** [comment]
wired, I have tested the development branch using  my test workflow to join and run, that worked fine also. could you please share your workflow here?

**Comment by schuelet** [comment]
I was testing development and 4.0. Here is a workflow.

[https://app.zenhub.com/files/241333403/806ffa3f-e535-4198-9b56-b8add83427fd/download](https://app.zenhub.com/files/241333403/806ffa3f-e535-4198-9b56-b8add83427fd/download)

**Comment by schuelet** [comment]
I reproduced the error with an untouched 4.0 branch. Here is the workflow. @ahmadswaid Please have a look in the debugger when executing the Runner and check if the parameters for the firstFskPortObject (combinedFskPortObject) are correct.

 Sorry for the inconvenience.

[https://app.zenhub.com/files/241333403/b00b9db2-922b-4ad6-a9f0-064154585168/download](https://app.zenhub.com/files/241333403/b00b9db2-922b-4ad6-a9f0-064154585168/download)

**Comment by ahmadswaid** [comment]
Also, I don't l consider that an error but correct 'by design' behavior.
each time you add one more level of joining the parameter's IDs from all joined models with their relation metadata will be updated to the IDs of the top level ones if they are from the same model. in this case if I have in the top level model a parameter X11 which comes from the first model(combined) you will find both have the same name.
this is important to have only one parameter at the end from the original source.
and the only important thing is to have consistency between the join model and its join-relation metadata.

**Comment by schuelet** [comment]
Thanks for the explanation, I think I understand now. Closing this then.
