### ISSUE TITLE
Expose joining algorithm with KNIME requests API

### ISSUE THREAD

**Issue by miguelalba** [RakipInitiative/ModelRepository#244]
The current implementation with the FskService does not work on the server. Implement it like in the Javascript Table View. See https://github.com/SiLeBAT/FSK-Lab/pull/771/

**Comment by mfilter** [comment]
Please check if this is a real issue, If not, lower the prio.

**Comment by schuelet** [comment]
As far as I can see, it is still a problem. The joiner works but KNIME generates a ton of csp reports because the lokalhost is called a lot. @ahmadswaid I believe, this makes the Component very unstable, at some point I had to restart the KNIME server because it blocked all FSK nodes (not sure if related though).
