### ISSUE TITLE
Component issue: on server, the component as implemented can't deal with file paths.

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#314]
- exact same models joined with Component and Joiner Node
- in the Component outport object the EnvironmentManager for the second model is empty, thus the model can't load its resources.

workflow: 
knime://external-KNIME-Server/FSKX_Testing/FSK-Lab_2.0/broken_workflows/JoinerComponent_missing_environment

**Comment by ahmadswaid** [comment]
@schuelet:
the Issue is in the workflow where some path manipulation is applied and make it impossible to read the file later in the joiner to recreate the enveiroment, this can be fixed by doing the same as:
knime://knime.mountpoint/FSKX_Testing/FSK-Lab_2.0/JoinerComponent_WorkflowPathExample
one requirment is that `Location` column which point to the file location on disk.

**Comment by schuelet** [comment]
@ahmadswaid I see what you mean, but the Location does not work when using the KNIME server. The list files/folders node only creates URL's, not file paths, so I had to do the path manipulation you mentioned. 
I agree it is a workflow problem, not necessarily a Component problem.

**Comment by schuelet** [comment]
fixed by removing "file:" prefix from Location. 
Moved workflow to knime://external-KNIME-Server/FSKX_Testing/FSK-Lab_2.0/fixed_broken_workflows/JoinerComponent_missing_environment
