### ISSUE TITLE
Execute failed: ("Exception"): null when writing file

### ISSUE THREAD

**Issue by arno314** [RakipInitiative/ModelRepository#468]
Rename the attached file to .fskx
In fsk-lab read it with fsk-reader and write directly with fsk-writer.
I get: Execute failed: ("Exception"): null when writing file

[Trichinella_meatProduction_0.6.zip](https://github.com/RakipInitiative/ModelRepository/files/10839132/Trichinella_meatProduction_0.6.zip)

**Comment by schuelet** [comment]
@arno314 This happens when the output filename is the same as the file currently opened by the Reader. I need to investigate why exactly the error is thrown, and there should definitely be a better error message, but I wonder if this behavior (don't overwrite the currently opened model) is worth keeping? Considering there could be something wrong with the new model file, better to keep the old one?.

**Comment by arno314** [comment]
@schuelet Can knime have popups? Then we can have "Overwrite yes/no?". Alternatively, a backup file of the old file could be made, e.g. with .fskx.bak extension, and a warning that a file was overwritten and a backup created.

**Comment by schuelet** [comment]
Fixed. Now, the writing process will be done on a copy of the original file. This way, only after everything is completed the original file will be overwritten.
